language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - DRUPAL_VERSION="~8.2.0-dev" ENTITY_VERSION="1.x-dev"

matrix:
  allow_failures:
    # We cannot use hhvm-nightly since that does not work in Travis CI's old
    # Ubuntu 12.04.
    - php: hhvm

  # Don't wait for the allowed failures to build.
  fast_finish: true

mysql:
  database: ceb
  username: root
  encoding: utf8

install:
  # Remove Xdebug.
  - phpenv config-rm xdebug.ini || true
  # Install drupal with composer.
  - composer create-project drupal/drupal drupal "$DRUPAL_VERSION" --no-interaction && cd drupal
  - composer config repositories.drupal composer https://packages.drupal.org/8
  - composer require drupal/entity:$ENTITY_VERSION

before_script:
  # Remember the current content_entity_base test directory for later use in the Drupal
  # installation.
  - TESTDIR=$(pwd)
  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Create database.
  - mysql -e 'create database ceb'

  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/ceb
  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://localhost:8888

  # Reference ceb in build site.
  - ln -s $TESTDIR modules/content_entity_base

  # Start a web server on port 8888, run in the background; wait for
  # initialization.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - ./vendor/phpunit/phpunit/phpunit -c ./core/phpunit.xml.dist --verbose ./modules/content_entity_base
