language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.1
  - hhvm

env:
  global: 
    # The name of the moduel to run tests on (this module).
    - DRUPAL_MODULE=content_entity_base
    # Database variable for kernel tests.
    - SIMPLETEST_DB="mysql://root:@127.0.0.1/drupal"
    # Web server URL for browser tests.
    - SIMPLETEST_BASE_URL="http://localhost:8888"
  matrix:
    - DRUPAL_VERSION="~8.1.0" ENTITY_VERSION="1.x-dev"
    - DRUPAL_VERSION="~8.2.0-dev" ENTITY_VERSION="1.x-dev"

matrix:
  allow_failures:
    # We cannot use hhvm-nightly since that does not work in Travis CI's old
    # Ubuntu 12.04.
    - php: hhvm
    - env: DRUPAL_VERSION="~8.1.0" ENTITY_VERSION="1.x-dev"

  # Don't wait for the allowed failures to build.
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Remove Xdebug.
  - phpenv config-rm xdebug.ini || true
  # Create database.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' -uroot

  # Navigate out of module directory to prevent blown stack by recursive module lookup.
  - cd ..

  # Install drupal and dependent modules with composer.
  - composer create-project drupal/drupal drupal "$DRUPAL_VERSION" --no-interaction && cd drupal
  - composer config repositories.drupal composer https://packages.drupal.org/8
  - composer require drupal/entity:$ENTITY_VERSION

  # Reference module in build site.
  - ln -s $TRAVIS_BUILD_DIR modules/$DRUPAL_MODULE

before_script:
  # Start a web server on port 8888, run in the background; wait for
  # initialization.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - ./vendor/phpunit/phpunit/phpunit -c ./core/phpunit.xml.dist --verbose ./modules/$DRUPAL_MODULE
